import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
import StoreProvider from "./StoreProvider";
import { FC, ReactNode } from "react";
import Sidebar from "@/components/organism/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        style={{
          // background: "rgb(158,201,182)",
          background:
            "linear-gradient(90deg, rgba(158,201,182,1) 0%, rgba(255,242,236,1) 66%, rgba(198,200,238,1) 100%)",
        }}
      >
        <StoreProvider>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              {/* <Header /> */}

              <Sidebar />
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
